runtime: java11
entrypoint: java -Xmx64m -war tweetfilteredAPI-0.0.1-SNAPSHOT.war

resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5